services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: sustentabag-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sacola_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sustentabag-network  # API da Sustentabag
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustentabag-api
    restart: unless-stopped
    ports:
      - "4041:4041"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=4041
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sacola_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA=public
      - JWT_SECRET=sustentabag_secret_key
      - JWT_EXPIRATION=24h
      - RABBITMQ=amqp://admin:admin@rabbitmq:5672
      # Firebase Configuration - using explicit values for reliability
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}      
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      # Private key needs special handling for newlines
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sustentabag-network

  # Ferramenta de administração do banco de dados
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sustentabag-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sustentabag.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - sustentabag-network
      
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    networks:
      - sustentabag-network

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    restart: unless-stopped
    ports:
      - "4409:4409"
    env_file:
      - ../notification-service/.env
    environment:
      - NODE_ENV=development
      - RABBITMQ=amqp://admin:admin@rabbitmq:5672
      - MAX_RETRIES=5
      - HEALTH_PORT=4409
      - PORT=4409
      - LOG_LEVEL=info
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    depends_on:
      - rabbitmq
    networks:
      - sustentabag-network

  mongodb:
    image: mongo:6.0
    container_name: payment-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: payment-service
    volumes:
      - mongodb_data:/data/db
    networks:
      - sustentabag-network

  # Serviço de pagamento
  payment-service:
    build:
      context: ../payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/payment-service
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672      
      - PAYMENT_SIMULATION_CALLBACK_URL=http://sustentabag-api:4041/api/payment-simulation
      - PAYMENT_SIMULATION_NOTIFICATION_URL=http://sustentabag-api:4041/api/payments/webhook
      - MONOLITH_BASE_URL=http://sustentabag-api:4041
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - sustentabag-network

  # Frontend Web Application
  sustenta-bag-web:
    build:
      context: ../sustenta-bag-web
      dockerfile: Dockerfile
    container_name: sustenta-bag-web
    restart: unless-stopped
    ports:
      - "4079:4079"
    env_file:
      - ../sustenta-bag-web/.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_BASE_URL=http://sustentabag-api:4041/api
      - REACT_APP_FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - REACT_APP_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - REACT_APP_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - REACT_APP_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - REACT_APP_FIREBASE_APP_ID=${FIREBASE_APP_ID}
    depends_on:
      - api
    networks:
      - sustentabag-network

volumes:
  postgres_data:
    name: sustentabag-postgres-data
  pgadmin_data:
    name: sustentabag-pgadmin-data
  mongodb_data:
    name: payment-mongodb-data

networks:
  sustentabag-network:
    name: sustentabag-network
    driver: bridge