name: "CI Pipeline"

on:
  push:
    branches: [ main, master, develop, feature/* ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Testes Unitários
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Instalar dependências
        run: npm ci
        
      - name: Executar testes
        run: npm test
        
      - name: Gerar relatório de cobertura de código
        run: npm run test:coverage || echo "Cobertura de testes falhou, mas continuando" 